//
//  Task.swift
//  greenlake-companion
//
//  Created by Savio Enoson on 01/09/25.
//


import Foundation

struct LandscapingTask: Identifiable, Hashable {
    let id = UUID()
    let imageName: String
    let title: String
    let description: String
    
    let taskType: TaskType
    let urgency: UrgencyLabel
    let plantType: PlantType
    let status: TaskStatus
    
    let dateCreated: Date
    let dateModified: Date?
    let dateClosed: Date?
}

let sampleTasks: [LandscapingTask] = [
    // MARK: - Major, Segera
    // Pohon
    LandscapingTask(imageName: "tree.fill", title: "Major task for Pohon", description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.", taskType: .major, urgency: .segera, plantType: .tree, status: .aktif, dateCreated: Date(timeIntervalSince1970: 1750599933), dateModified: Date(timeIntervalSince1970: 1750945533), dateClosed: nil),
    LandscapingTask(imageName: "tree.fill", title: "Major task for Pohon", description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.", taskType: .major, urgency: .segera, plantType: .tree, status: .diajukan, dateCreated: Date(timeIntervalSince1970: 1750005789), dateModified: Date(timeIntervalSince1970: 1750178589), dateClosed: nil),
    LandscapingTask(imageName: "tree.fill", title: "Major task for Pohon", description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.", taskType: .major, urgency: .segera, plantType: .tree, status: .diperiksa, dateCreated: Date(timeIntervalSince1970: 1749112998), dateModified: Date(timeIntervalSince1970: 1749372198), dateClosed: nil),
    LandscapingTask(imageName: "tree.fill", title: "Major task for Pohon", description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.", taskType: .major, urgency: .segera, plantType: .tree, status: .selesai, dateCreated: Date(timeIntervalSince1970: 1749502941), dateModified: Date(timeIntervalSince1970: 1749675741), dateClosed: Date(timeIntervalSince1970: 1750021341)),
    LandscapingTask(imageName: "tree.fill", title: "Major task for Pohon", description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.", taskType: .major, urgency: .segera, plantType: .tree, status: .terdenda, dateCreated: Date(timeIntervalSince1970: 1751139459), dateModified: Date(timeIntervalSince1970: 1751571459), dateClosed: Date(timeIntervalSince1970: 1751830659)),
    LandscapingTask(imageName: "tree.fill", title: "Major task for Pohon", description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.", taskType: .major, urgency: .segera, plantType: .tree, status: .dialihkan, dateCreated: Date(timeIntervalSince1970: 1750098939), dateModified: Date(timeIntervalSince1970: 1750530939), dateClosed: nil),
    // Semak
    LandscapingTask(imageName: "cloud.fill", title: "Major task for Semak", description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.", taskType: .major, urgency: .segera, plantType: .bush, status: .aktif, dateCreated: Date(timeIntervalSince1970: 1749747949), dateModified: Date(timeIntervalSince1970: 1750093549), dateClosed: nil),
    LandscapingTask(imageName: "cloud.fill", title: "Major task for Semak", description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.", taskType: .major, urgency: .segera, plantType: .bush, status: .diajukan, dateCreated: Date(timeIntervalSince1970: 1750861111), dateModified: Date(timeIntervalSince1970: 1751120311), dateClosed: nil),
    LandscapingTask(imageName: "cloud.fill", title: "Major task for Semak", description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.", taskType: .major, urgency: .segera, plantType: .bush, status: .diperiksa, dateCreated: Date(timeIntervalSince1970: 1750125868), dateModified: Date(timeIntervalSince1970: 1750557868), dateClosed: nil),
    LandscapingTask(imageName: "cloud.fill", title: "Major task for Semak", description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.", taskType: .major, urgency: .segera, plantType: .bush, status: .selesai, dateCreated: Date(timeIntervalSince1970: 1749454888), dateModified: Date(timeIntervalSince1970: 1749800488), dateClosed: Date(timeIntervalSince1970: 1750232488)),
    LandscapingTask(imageName: "cloud.fill", title: "Major task for Semak", description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.", taskType: .major, urgency: .segera, plantType: .bush, status: .terdenda, dateCreated: Date(timeIntervalSince1970: 1750245050), dateModified: Date(timeIntervalSince1970: 1750677050), dateClosed: Date(timeIntervalSince1970: 1750936250)),
    LandscapingTask(imageName: "cloud.fill", title: "Major task for Semak", description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.", taskType: .major, urgency: .segera, plantType: .bush, status: .dialihkan, dateCreated: Date(timeIntervalSince1970: 1749811408), dateModified: Date(timeIntervalSince1970: 1749984208), dateClosed: nil),
    // Ground Cover
    LandscapingTask(imageName: "camera.macro", title: "Major task for Ground Cover", description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.", taskType: .major, urgency: .segera, plantType: .groundCover, status: .aktif, dateCreated: Date(timeIntervalSince1970: 1750035588), dateModified: Date(timeIntervalSince1970: 1750381188), dateClosed: nil),
    LandscapingTask(imageName: "camera.macro", title: "Major task for Ground Cover", description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.", taskType: .major, urgency: .segera, plantType: .groundCover, status: .diajukan, dateCreated: Date(timeIntervalSince1970: 1749320603), dateModified: Date(timeIntervalSince1970: 1749752603), dateClosed: nil),
    LandscapingTask(imageName: "camera.macro", title: "Major task for Ground Cover", description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.", taskType: .major, urgency: .segera, plantType: .groundCover, status: .diperiksa, dateCreated: Date(timeIntervalSince1970: 1749666014), dateModified: Date(timeIntervalSince1970: 1749925214), dateClosed: nil),
    LandscapingTask(imageName: "camera.macro", title: "Major task for Ground Cover", description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.", taskType: .major, urgency: .segera, plantType: .groundCover, status: .selesai, dateCreated: Date(timeIntervalSince1970: 1750679893), dateModified: Date(timeIntervalSince1970: 1751111893), dateClosed: Date(timeIntervalSince1970: 1751457493)),
    LandscapingTask(imageName: "camera.macro", title: "Major task for Ground Cover", description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.", taskType: .major, urgency: .segera, plantType: .groundCover, status: .terdenda, dateCreated: Date(timeIntervalSince1970: 1749890184), dateModified: Date(timeIntervalSince1970: 1750062984), dateClosed: Date(timeIntervalSince1970: 1750408584)),
    LandscapingTask(imageName: "camera.macro", title: "Major task for Ground Cover", description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.", taskType: .major, urgency: .segera, plantType: .groundCover, status: .dialihkan, dateCreated: Date(timeIntervalSince1970: 1750240428), dateModified: Date(timeIntervalSince1970: 1750413228), dateClosed: nil),
    
    // MARK: - Major, Normal
    // Pohon
    LandscapingTask(imageName: "tree.fill", title: "Major task for Pohon", description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.", taskType: .major, urgency: .normal, plantType: .tree, status: .aktif, dateCreated: Date(timeIntervalSince1970: 1749504841), dateModified: Date(timeIntervalSince1970: 1749936841), dateClosed: nil),
    LandscapingTask(imageName: "tree.fill", title: "Major task for Pohon", description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.", taskType: .major, urgency: .normal, plantType: .tree, status: .diajukan, dateCreated: Date(timeIntervalSince1970: 1750012294), dateModified: Date(timeIntervalSince1970: 1750185094), dateClosed: nil),
    LandscapingTask(imageName: "tree.fill", title: "Major task for Pohon", description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.", taskType: .major, urgency: .normal, plantType: .tree, status: .diperiksa, dateCreated: Date(timeIntervalSince1970: 1750534241), dateModified: Date(timeIntervalSince1970: 1750966241), dateClosed: nil),
    LandscapingTask(imageName: "tree.fill", title: "Major task for Pohon", description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.", taskType: .major, urgency: .normal, plantType: .tree, status: .selesai, dateCreated: Date(timeIntervalSince1970: 1750186938), dateModified: Date(timeIntervalSince1970: 1750618938), dateClosed: Date(timeIntervalSince1970: 1751050938)),
    LandscapingTask(imageName: "tree.fill", title: "Major task for Pohon", description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.", taskType: .major, urgency: .normal, plantType: .tree, status: .terdenda, dateCreated: Date(timeIntervalSince1970: 1750796859), dateModified: Date(timeIntervalSince1970: 1751056059), dateClosed: Date(timeIntervalSince1970: 1751315259)),
    LandscapingTask(imageName: "tree.fill", title: "Major task for Pohon", description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.", taskType: .major, urgency: .normal, plantType: .tree, status: .dialihkan, dateCreated: Date(timeIntervalSince1970: 1749830500), dateModified: Date(timeIntervalSince1970: 1750176100), dateClosed: nil),
    // Semak
    LandscapingTask(imageName: "cloud.fill", title: "Major task for Semak", description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.", taskType: .major, urgency: .normal, plantType: .bush, status: .aktif, dateCreated: Date(timeIntervalSince1970: 1750146957), dateModified: Date(timeIntervalSince1970: 1750578957), dateClosed: nil),
    LandscapingTask(imageName: "cloud.fill", title: "Major task for Semak", description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.", taskType: .major, urgency: .normal, plantType: .bush, status: .diajukan, dateCreated: Date(timeIntervalSince1970: 1749774672), dateModified: Date(timeIntervalSince1970: 1750206672), dateClosed: nil),
    LandscapingTask(imageName: "cloud.fill", title: "Major task for Semak", description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.", taskType: .major, urgency: .normal, plantType: .bush, status: .diperiksa, dateCreated: Date(timeIntervalSince1970: 1749558369), dateModified: Date(timeIntervalSince1970: 1749817569), dateClosed: nil),
    LandscapingTask(imageName: "cloud.fill", title: "Major task for Semak", description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.", taskType: .major, urgency: .normal, plantType: .bush, status: .selesai, dateCreated: Date(timeIntervalSince1970: 1750392305), dateModified: Date(timeIntervalSince1970: 1750737905), dateClosed: Date(timeIntervalSince1970: 1750997105)),
    LandscapingTask(imageName: "cloud.fill", title: "Major task for Semak", description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.", taskType: .major, urgency: .normal, plantType: .bush, status: .terdenda, dateCreated: Date(timeIntervalSince1970: 1749216065), dateModified: Date(timeIntervalSince1970: 1749388865), dateClosed: Date(timeIntervalSince1970: 1749820865)),
    LandscapingTask(imageName: "cloud.fill", title: "Major task for Semak", description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.", taskType: .major, urgency: .normal, plantType: .bush, status: .dialihkan, dateCreated: Date(timeIntervalSince1970: 1750917616), dateModified: Date(timeIntervalSince1970: 1751263216), dateClosed: nil),
    // Ground Cover
    LandscapingTask(imageName: "camera.macro", title: "Major task for Ground Cover", description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.", taskType: .major, urgency: .normal, plantType: .groundCover, status: .aktif, dateCreated: Date(timeIntervalSince1970: 1749313936), dateModified: Date(timeIntervalSince1970: 1749745936), dateClosed: nil),
    LandscapingTask(imageName: "camera.macro", title: "Major task for Ground Cover", description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.", taskType: .major, urgency: .normal, plantType: .groundCover, status: .diajukan, dateCreated: Date(timeIntervalSince1970: 1750794539), dateModified: Date(timeIntervalSince1970: 1750967339), dateClosed: nil),
    LandscapingTask(imageName: "camera.macro", title: "Major task for Ground Cover", description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.", taskType: .major, urgency: .normal, plantType: .groundCover, status: .diperiksa, dateCreated: Date(timeIntervalSince1970: 1749842407), dateModified: Date(timeIntervalSince1970: 1750188007), dateClosed: nil),
    LandscapingTask(imageName: "camera.macro", title: "Major task for Ground Cover", description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.", taskType: .major, urgency: .normal, plantType: .groundCover, status: .selesai, dateCreated: Date(timeIntervalSince1970: 1750379445), dateModified: Date(timeIntervalSince1970: 1750725045), dateClosed: Date(timeIntervalSince1970: 1750984245)),
    LandscapingTask(imageName: "camera.macro", title: "Major task for Ground Cover", description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.", taskType: .major, urgency: .normal, plantType: .groundCover, status: .terdenda, dateCreated: Date(timeIntervalSince1970: 1749557870), dateModified: Date(timeIntervalSince1970: 1749730670), dateClosed: Date(timeIntervalSince1970: 1749989870)),
    LandscapingTask(imageName: "camera.macro", title: "Major task for Ground Cover", description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.", taskType: .major, urgency: .normal, plantType: .groundCover, status: .dialihkan, dateCreated: Date(timeIntervalSince1970: 1750800619), dateModified: Date(timeIntervalSince1970: 1751146219), dateClosed: nil),

    // MARK: - Minor, Segera
    // Pohon
    LandscapingTask(imageName: "tree.fill", title: "Minor task for Pohon", description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.", taskType: .minor, urgency: .segera, plantType: .tree, status: .aktif, dateCreated: Date(timeIntervalSince1970: 1750314488), dateModified: Date(timeIntervalSince1970: 1750746488), dateClosed: nil),
    LandscapingTask(imageName: "tree.fill", title: "Minor task for Pohon", description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.", taskType: .minor, urgency: .segera, plantType: .tree, status: .diajukan, dateCreated: Date(timeIntervalSince1970: 1750536735), dateModified: Date(timeIntervalSince1970: 1750623135), dateClosed: nil),
    LandscapingTask(imageName: "tree.fill", title: "Minor task for Pohon", description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.", taskType: .minor, urgency: .segera, plantType: .tree, status: .diperiksa, dateCreated: Date(timeIntervalSince1970: 1749567936), dateModified: Date(timeIntervalSince1970: 1749827136), dateClosed: nil),
    LandscapingTask(imageName: "tree.fill", title: "Minor task for Pohon", description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.", taskType: .minor, urgency: .segera, plantType: .tree, status: .selesai, dateCreated: Date(timeIntervalSince1970: 1750849317), dateModified: Date(timeIntervalSince1970: 1751022117), dateClosed: Date(timeIntervalSince1970: 1751367717)),
    LandscapingTask(imageName: "tree.fill", title: "Minor task for Pohon", description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.", taskType: .minor, urgency: .segera, plantType: .tree, status: .terdenda, dateCreated: Date(timeIntervalSince1970: 1749845899), dateModified: Date(timeIntervalSince1970: 1750191499), dateClosed: Date(timeIntervalSince1970: 1750364299)),
    LandscapingTask(imageName: "tree.fill", title: "Minor task for Pohon", description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.", taskType: .minor, urgency: .segera, plantType: .tree, status: .dialihkan, dateCreated: Date(timeIntervalSince1970: 1750247656), dateModified: Date(timeIntervalSince1970: 1750679656), dateClosed: nil),
    // Semak
    LandscapingTask(imageName: "cloud.fill", title: "Minor task for Semak", description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.", taskType: .minor, urgency: .segera, plantType: .bush, status: .aktif, dateCreated: Date(timeIntervalSince1970: 1750199321), dateModified: Date(timeIntervalSince1970: 1750372121), dateClosed: nil),
    LandscapingTask(imageName: "cloud.fill", title: "Minor task for Semak", description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.", taskType: .minor, urgency: .segera, plantType: .bush, status: .diajukan, dateCreated: Date(timeIntervalSince1970: 1749286820), dateModified: Date(timeIntervalSince1970: 1749718820), dateClosed: nil),
    LandscapingTask(imageName: "cloud.fill", title: "Minor task for Semak", description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.", taskType: .minor, urgency: .segera, plantType: .bush, status: .diperiksa, dateCreated: Date(timeIntervalSince1970: 1750796328), dateModified: Date(timeIntervalSince1970: 1751228328), dateClosed: nil),
    LandscapingTask(imageName: "cloud.fill", title: "Minor task for Semak", description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.", taskType: .minor, urgency: .segera, plantType: .bush, status: .selesai, dateCreated: Date(timeIntervalSince1970: 1749909241), dateModified: Date(timeIntervalSince1970: 1750168441), dateClosed: Date(timeIntervalSince1970: 1750514041)),
    LandscapingTask(imageName: "cloud.fill", title: "Minor task for Semak", description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.", taskType: .minor, urgency: .segera, plantType: .bush, status: .terdenda, dateCreated: Date(timeIntervalSince1970: 1750007887), dateModified: Date(timeIntervalSince1970: 1750180687), dateClosed: Date(timeIntervalSince1970: 1750439887)),
    LandscapingTask(imageName: "cloud.fill", title: "Minor task for Semak", description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.", taskType: .minor, urgency: .segera, plantType: .bush, status: .dialihkan, dateCreated: Date(timeIntervalSince1970: 1749221193), dateModified: Date(timeIntervalSince1970: 1749393993), dateClosed: nil),
    // Ground Cover
    LandscapingTask(imageName: "camera.macro", title: "Minor task for Ground Cover", description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.", taskType: .minor, urgency: .segera, plantType: .groundCover, status: .aktif, dateCreated: Date(timeIntervalSince1970: 1750371661), dateModified: Date(timeIntervalSince1970: 1750803661), dateClosed: nil),
    LandscapingTask(imageName: "camera.macro", title: "Minor task for Ground Cover", description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.", taskType: .minor, urgency: .segera, plantType: .groundCover, status: .diajukan, dateCreated: Date(timeIntervalSince1970: 1751111046), dateModified: Date(timeIntervalSince1970: 1751456646), dateClosed: nil),
    LandscapingTask(imageName: "camera.macro", title: "Minor task for Ground Cover", description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.", taskType: .minor, urgency: .segera, plantType: .groundCover, status: .diperiksa, dateCreated: Date(timeIntervalSince1970: 1749138407), dateModified: Date(timeIntervalSince1970: 1749224807), dateClosed: nil),
    LandscapingTask(imageName: "camera.macro", title: "Minor task for Ground Cover", description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.", taskType: .minor, urgency: .segera, plantType: .groundCover, status: .selesai, dateCreated: Date(timeIntervalSince1970: 1750592982), dateModified: Date(timeIntervalSince1970: 1750938582), dateClosed: Date(timeIntervalSince1970: 1751370582)),
    LandscapingTask(imageName: "camera.macro", title: "Minor task for Ground Cover", description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.", taskType: .minor, urgency: .segera, plantType: .groundCover, status: .terdenda, dateCreated: Date(timeIntervalSince1970: 1749764506), dateModified: Date(timeIntervalSince1970: 1750023706), dateClosed: Date(timeIntervalSince1970: 1750369306)),
    LandscapingTask(imageName: "camera.macro", title: "Minor task for Ground Cover", description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.", taskType: .minor, urgency: .segera, plantType: .groundCover, status: .dialihkan, dateCreated: Date(timeIntervalSince1970: 1749479905), dateModified: Date(timeIntervalSince1970: 1749911905), dateClosed: nil),
    
    // MARK: - Minor, Normal
    // Pohon
    LandscapingTask(imageName: "tree.fill", title: "Minor task for Pohon", description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.", taskType: .minor, urgency: .normal, plantType: .tree, status: .aktif, dateCreated: Date(timeIntervalSince1970: 1749219665), dateModified: Date(timeIntervalSince1970: 1749478865), dateClosed: nil),
    LandscapingTask(imageName: "tree.fill", title: "Minor task for Pohon", description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.", taskType: .minor, urgency: .normal, plantType: .tree, status: .diajukan, dateCreated: Date(timeIntervalSince1970: 1750392398), dateModified: Date(timeIntervalSince1970: 1750737998), dateClosed: nil),
    LandscapingTask(imageName: "tree.fill", title: "Minor task for Pohon", description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.", taskType: .minor, urgency: .normal, plantType: .tree, status: .diperiksa, dateCreated: Date(timeIntervalSince1970: 1750106203), dateModified: Date(timeIntervalSince1970: 1750279003), dateClosed: nil),
    LandscapingTask(imageName: "tree.fill", title: "Minor task for Pohon", description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.", taskType: .minor, urgency: .normal, plantType: .tree, status: .selesai, dateCreated: Date(timeIntervalSince1970: 1750974868), dateModified: Date(timeIntervalSince1970: 1751147668), dateClosed: Date(timeIntervalSince1970: 1751493268)),
    LandscapingTask(imageName: "tree.fill", title: "Minor task for Pohon", description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.", taskType: .minor, urgency: .normal, plantType: .tree, status: .terdenda, dateCreated: Date(timeIntervalSince1970: 1750486842), dateModified: Date(timeIntervalSince1970: 1750746042), dateClosed: Date(timeIntervalSince1970: 1750918842)),
    LandscapingTask(imageName: "tree.fill", title: "Minor task for Pohon", description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.", taskType: .minor, urgency: .normal, plantType: .tree, status: .dialihkan, dateCreated: Date(timeIntervalSince1970: 1749323145), dateModified: Date(timeIntervalSince1970: 1749582345), dateClosed: nil),
    // Semak
    LandscapingTask(imageName: "cloud.fill", title: "Minor task for Semak", description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.", taskType: .minor, urgency: .normal, plantType: .bush, status: .aktif, dateCreated: Date(timeIntervalSince1970: 1749873099), dateModified: Date(timeIntervalSince1970: 1750132299), dateClosed: nil),
    LandscapingTask(imageName: "cloud.fill", title: "Minor task for Semak", description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.", taskType: .minor, urgency: .normal, plantType: .bush, status: .diajukan, dateCreated: Date(timeIntervalSince1970: 1749969116), dateModified: Date(timeIntervalSince1970: 1750314716), dateClosed: nil),
    LandscapingTask(imageName: "cloud.fill", title: "Minor task for Semak", description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.", taskType: .minor, urgency: .normal, plantType: .bush, status: .diperiksa, dateCreated: Date(timeIntervalSince1970: 1750462791), dateModified: Date(timeIntervalSince1970: 1750635591), dateClosed: nil),
    LandscapingTask(imageName: "cloud.fill", title: "Minor task for Semak", description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.", taskType: .minor, urgency: .normal, plantType: .bush, status: .selesai, dateCreated: Date(timeIntervalSince1970: 1750692790), dateModified: Date(timeIntervalSince1970: 1751124790), dateClosed: Date(timeIntervalSince1970: 1751383990)),
    LandscapingTask(imageName: "cloud.fill", title: "Minor task for Semak", description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.", taskType: .minor, urgency: .normal, plantType: .bush, status: .terdenda, dateCreated: Date(timeIntervalSince1970: 1749323631), dateModified: Date(timeIntervalSince1970: 1749400031), dateClosed: Date(timeIntervalSince1970: 1749745631)),
    LandscapingTask(imageName: "cloud.fill", title: "Minor task for Semak", description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.", taskType: .minor, urgency: .normal, plantType: .bush, status: .dialihkan, dateCreated: Date(timeIntervalSince1970: 1749500096), dateModified: Date(timeIntervalSince1970: 1749759296), dateClosed: nil),
    // Ground Cover
    LandscapingTask(imageName: "camera.macro", title: "Minor task for Ground Cover", description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.", taskType: .minor, urgency: .normal, plantType: .groundCover, status: .aktif, dateCreated: Date(timeIntervalSince1970: 1750897281), dateModified: Date(timeIntervalSince1970: 1751156481), dateClosed: nil),
    LandscapingTask(imageName: "camera.macro", title: "Minor task for Ground Cover", description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.", taskType: .minor, urgency: .normal, plantType: .groundCover, status: .diajukan, dateCreated: Date(timeIntervalSince1970: 1749557288), dateModified: Date(timeIntervalSince1970: 1749730088), dateClosed: nil),
    LandscapingTask(imageName: "camera.macro", title: "Minor task for Ground Cover", description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.", taskType: .minor, urgency: .normal, plantType: .groundCover, status: .diperiksa, dateCreated: Date(timeIntervalSince1970: 1751079541), dateModified: Date(timeIntervalSince1970: 1751252341), dateClosed: nil),
    LandscapingTask(imageName: "camera.macro", title: "Minor task for Ground Cover", description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.", taskType: .minor, urgency: .normal, plantType: .groundCover, status: .selesai, dateCreated: Date(timeIntervalSince1970: 1750275825), dateModified: Date(timeIntervalSince1970: 1750707825), dateClosed: Date(timeIntervalSince1970: 1751139825)),
    LandscapingTask(imageName: "camera.macro", title: "Minor task for Ground Cover", description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.", taskType: .minor, urgency: .normal, plantType: .groundCover, status: .terdenda, dateCreated: Date(timeIntervalSince1970: 1749297298), dateModified: Date(timeIntervalSince1970: 1749470098), dateClosed: Date(timeIntervalSince1970: 1749815698)),
    LandscapingTask(imageName: "camera.macro", title: "Minor task for Ground Cover", description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.", taskType: .minor, urgency: .normal, plantType: .groundCover, status: .dialihkan, dateCreated: Date(timeIntervalSince1970: 1749867911), dateModified: Date(timeIntervalSince1970: 1750300000), dateClosed: nil)
]
